version: '3'
services:
  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:centos-5.4.0
    restart: always
    environment:
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=nYMoYub3r6tjhj
      - MYSQL_ROOT_PASSWORD=nYMoYub3r6tjhj
      - ZBX_SERVER_HOST=zabbix-server-mysql
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/zabbix/fonts/DejaVuSans.ttf:/usr/share/zabbix/assets/fonts/DejaVuSans.ttf
    networks:
      - zabbix_net
    depends_on:
      - zabbix-mysql
      - zabbix-server-mysql
  zabbix-mysql:
    image: mysql:8.0.23
    restart: always
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=nYMoYub3r6tjhj
      - MYSQL_ROOT_PASSWORD=nYMoYub3r6tjhj
    command:
      - mysqld
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_bin
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/zabbix/db:/var/lib/mysql
    networks:
      - zabbix_net
  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:centos-5.4.0
    restart: always
    volumes:
      - zabbix-server-vol:/etc/zabbix
      - /data/zabbix/alertscripts:/user/lib/zabbix/alertscripts
      - /etc/localtime:/etc/localtime
    ports:
      - 10051:10051
    environment:
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=nYMoYub3r6tjhj
      - MYSQL_ROOT_PASSWORD=nYMoYub3r6tjhj
    depends_on:
      - zabbix-mysql
    networks:
      - zabbix_net
  zabbix-agent:
    image: zabbix/zabbix-agent:centos-5.4.0
    restart: always
    ports:
      - 10050:10050
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=zabbix-server-mysql
      - ZBX_SERVER_PORT=10051
    networks:
      - zabbix_net


networks:
  zabbix_net:
    driver: bridge
volumes:
  zabbix-server-vol: